name: Build Release
on:
  release:
    types: [created]
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.21.x']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set env
        run: >-
          sudo apt-get update &&
          sudo apt-get install
          bc
          gcc
          libgl1-mesa-dev
          libwayland-dev
          libx11-dev
          libxkbcommon-dev
          xorg-dev
          xvfb
          wget https://github.com/upx/upx/releases/download/v4.0.2/upx-4.2.2-amd64_linux.tar.xz
          tar -Jxf upx*.tar.xz
          sudo cp upx*/upx /usr/bin
          go env -w GO111MODULE=on
          go install github.com/fyne-io/fyne-cross@latest
      - name: Package
        run: fyne-cross windows -arch=amd64,386 --appVersion 2.0 --release true