name: Release Build
on:
  release:
    types: [created]
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.21.x']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install
          bc
          gcc
          libgl1-mesa-dev
          libwayland-dev
          libx11-dev
          libxkbcommon-dev
          xorg-dev
          xvfb
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Package (windows)
        run: package -os windows --appVersion 2.0 --release true